{% set name = "nahrwhals" %}
{% set version = "1.1.beta" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WHops/NAHRwhals/archive/refs/tags/v1.1-beta.tar.gz
  sha256: 0e77310cddebd799eef95624c58bc7c1221dd1665a0399efd7b4af80f549ea3e

build:
  script: ${R} CMD INSTALL --build . ${R_ARGS}
  number: 0

requirements:
  build:

  host:
    - r-base >=4.2.3
    - r-ggplot2 >=3.3.6
    - r-dplyr >=1.1.2
    - r-scales >=1.2.0
    - r-matrixStats >=0.63.0
    - r-rcolorbrewer >=1.1-3
    - r-stringr >=1.4.0
    - r-ggrepel >=0.9.3
    - r-patchwork >=1.1.1
    - r-hash >=2.2.6.2
    - r-reshape2 >=1.4.4
    - r-rlang >=1.1.0
    - r-magrittr >=2.0.3
    - bioconductor-biostrings >=2.66.0
  run:
    - r-base >=4.2.3
    - r-ggplot2 >=3.3.6
    - r-dplyr >=1.1.2
    - r-scales >=1.2.0
    - r-matrixStats >=0.63.0
    - r-rcolorbrewer >=1.1-3
    - r-stringr >=1.4.0
    - r-ggrepel >=0.9.3
    - r-patchwork >=1.1.1
    - r-hash >=2.2.6.2
    - r-reshape2 >=1.4.4
    - r-rlang >=1.1.0
    - r-magrittr >=2.0.3
    - bioconda::minimap2 >=2.24
    - bioconda::bedtools
    - bioconductor-biostrings >=2.66.0

test:
  commands:
    - Rscript -e 'library("nahrwhals")'

about:
  home: https://github.com/WHops/NAHRwhals/
  summary: 'NAHRwhals (NAHR-directed Workflow for catcHing seriAL Structural Variations)'
  description: nahrwhals provides tools for visualization and detection of NAHR-driven rearrangements using genome assemblies.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - LisaSimpson
    - LandoCalrissian
